# Generated by Django 4.2.1 on 2023-05-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip адрес')),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.post', verbose_name='Публикация')),
            ],
        ),
    ]
