# Generated by Django 4.2.1 on 2023-05-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_name',
            new_name='pos',
        ),
    ]
